### ISSUE TITLE
About the baseline of the dqn policy.

### ISSUE THREAD

**Issue by liusih** [ConvLab/ConvLab#106]
Could you mind give the baseline result(successful rate...) when used the dqn as the dialogue policy? 
because when I run the original code with :
`python run.py demo.json onenet_rule_dqn_template train`
The final result is 
`100 episodes, -57.62 return, 1.00% success rate, 20.82 turns`
Thus， I would like to know that whether my result is not correct,or I shoud change some parameters to get a better perfomance.

Thanks.

**Comment by jincli** [comment]
@liusih   please check this issue. https://github.com/ConvLab/ConvLab/issues/33

**Comment by liusih** [comment]
> @liusih please check this issue. #33

Thanks for your replaying!

And by the way, would you mind providing some references you and your group have done to impove the dialogue sucessful rate on the MultiWoz dataset?

**Comment by carelvniekerk** [comment]
Hey
I am having the same issue and cannot seem to get to 30% success, this is using the rule_wdqn recommended setup from thread #33 . Do you have any recommendations on how I can get this to work?

**Comment by jincli** [comment]
@liusih  Please check https://arxiv.org/abs/2002.04793, and we will release the codebase of convlab-2 soon.

**Comment by liusih** [comment]
> @liusih Please check https://arxiv.org/abs/2002.04793, and we will release the codebase of convlab-2 soon.

Thank you so much!

**Comment by liusih** [comment]
@jincli Thank you so much!
