### ISSUE TITLE
Issue with the Demo Policies

### ISSUE THREAD

**Issue by carelvniekerk** [ConvLab/ConvLab#108]
Do you have any successful results training policies other than WDQN. I managed to train wdqn as adviced in #33, however when trying to train any other policies, like PPO for example I am unable to get any success.

Have you had any success with training these policies? If so could you give me some tips on what worked for you?

Thanks for your help.

**Comment by jincli** [comment]
@carelvniekerk  We didn't tune the parameters for RL algorithms in ConvLab. You can check the them in ConvLab-2: https://github.com/thu-coai/ConvLab-2
