### ISSUE TITLE
NameError: name 'false' is not defined

### ISSUE THREAD

**Issue by tristatl** [ConvLab/ConvLab#110]
I went through a tiny problem when I run the code with commad : 
python demo.json onenet_rule_dqn_template train
Then it throws below error :
Traceback (most recent call last):
  File "./convlab/spec/demo.json", line 14, in <module>
    "is_user": false
NameError: name 'false' is not defined

In fact I tried all the commad, it all ourrs the error.
I have no idea why. Please help me. Thanks.

**Comment by jincli** [comment]
@tristatl  Can you try 'python run.py demo.json milu_rule_wdqn_template train'? If it still does not work, probably try to git clone the repo to get a clean copy of code again.

**Comment by tristatl** [comment]
Thanks! That works. I git clone the repo again and rerun the code.
