### ISSUE TITLE
about DQN in Convlab2

### ISSUE THREAD

**Issue by sherlock1987** [ConvLab/ConvLab#113]
Hey, guys, are you guys planing to move DQN from Convlab1 to Convlab2? Since I am a big fan of Convlab2, so I really want to konw if DQN will work in Convlab2. And I am doing reward function for RL recently, I have to make more RL learing curve on my paper. 

Here are two reason that I think it may not work.
1. The action space (MultiWoz) in Convlab1 is just arond 300, and evaluation should follows that. But in Convlab2, there are no such small action space, it is so large, up to 8000.
2. When do evaluation, Convlab1 will only review the 300 actions, but for Convlab2, it will contains all of possible actions.

I am looking forward your reply, if Convlab2 not work, I have to move to Convlab1, which is not convinient for me since I have already done plenty of work on Convlab2.

**Comment by zqwerty** [comment]
Please see https://github.com/thu-coai/ConvLab-2/issues/59#issuecomment-663329647
