### ISSUE TITLE
Is there any method to speed up the training process?

### ISSUE THREAD

**Issue by sherlock1987** [ConvLab/ConvLab#115]
I try to train the warmup DQN, however, it will cost me about 2 hours to train one model. Is there any method to speed up the training process? I got one server, which contains 96 CPU unit, but it also run slow on that.

**Comment by jincli** [comment]
@sherlock1987  We have not tried speeding up the process, but since the tool already supports multi-processing, you might want to verify whether multi-processing is working correctly.

**Comment by sherlock1987** [comment]
Thanks for your reply, but how should I do that? For example, if I type python run.py, how could I specify that I want multi-process?

**Comment by sherlock1987** [comment]
By the way, I could see the multi_thread in run.py, this is different from you said multi-process right?

**Comment by jincli** [comment]
@sherlock1987   What I referred to is for code snippets associated with torch.multiprocessing

**Comment by sherlock1987** [comment]
Thanks for your reply, I think you refered to multi thread, right? Since I could only see code in run.py which is related to multi thread. 

```
if __name__ == '__main__':
    torch.set_num_threads(1)  # prevent multithread slowdown
    mp.set_start_method('spawn', force=True)  # for distributed pytorch to work
    if sys.platform == 'darwin':
        # avoid xvfb on MacOS: https://github.com/nipy/nipype/issues/1400
        main()
    else:
        #with Xvfb() as xvfb:  # safety context for headless machines
        main()
```

**Comment by jincli** [comment]
@sherlock1987  multithreading and multiprocessing are not necessarily the same thing, but the code snippet you pasted is definitely the start point to debug the performance.

**Comment by sherlock1987** [comment]
Okay, thanks!
