### ISSUE TITLE
Question: What is the meaning of max_session and max_trial?

### ISSUE THREAD

**Issue by sherlock1987** [ConvLab/ConvLab#117]
Hello, guys, I am confused about the  meaning of max_session and max_trial in spec/demo.json. And also,   

```
"resources": 
     {
        "num_cpus": 1,
        "num_gpus": 0
      }
```

This resources seems like has no influence when I make the num_cpu/num_gpu larger.

**Comment by sherlock1987** [comment]
And also, same in spec/demo.json,

"algorithm": {
        "name": "PPO",
        ..........
        ..........
        "gpu": false
I find that when I set gpu to true, this code will also run on GPU, but like you guys said, all of the codes is only run on CPU, so what kind influence will have after set "gpu" to true?

**Comment by jincli** [comment]
@sherlock1987  
- We inherited the RL framework from SLM-Lab, so you can check the detailed framework explanation here https://slm-lab.gitbo
- The gpu setting under 'net' in config is inherited from SLM-Lab, so you might find it working. When we developed ConvLab, some models support gpu, while some only support cpu. But in terms of testing, we only tested ConvLab thoroughly on cpu.

**Comment by sherlock1987** [comment]
Okay, I got the answer, max_session is a independent experiment. And max_trail related to how many times should we try, like how many max_session you will run.

**Comment by sherlock1987** [comment]
By the way, could some one tell me how to do grid search? I believe the grid serach is implemented in this platform, is that right?

**Comment by jincli** [comment]
@sherlock1987  You can refer to https://github.com/kengz/SLM-Lab/blob/master/slm_lab/spec/demo.json
