### ISSUE TITLE
what is the difference between eval mode and model with evaluator?

### ISSUE THREAD

**Issue by qazwsx74269** [ConvLab/ConvLab#29]

**Comment by sungjinl** [comment]
@qazwsx74269, thanks for your question.

With the eval mode, you can evaluate your dialog system with the user simulator whereas you can train one of RL agents with the train mode.

Evaluator is an independent of eval mode in that it is a class implementing code for judging domain-specific task success. You should use the evaluator for both training and evaluation.

Hope this makes sense to you.
