### ISSUE TITLE
How to measure success rate? function "task_complate" in policy_agenda_multiwoz.py

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#30]
Hi,

This is the evaluation code(gen_avg_result in convlab/experiment/analysis.py) and I want to know how to measure "success_rate".
![gen_avg_result](https://user-images.githubusercontent.com/16661213/60870973-d24dea00-a26c-11e9-8b45-f05d10f18cbb.png)

To check how to measure "success_rate", I thought "task_complete" in convlab/modules/policy/user/multiwoz/policy_agenda_multiwoz.py is core function I guessed. (in eval mode)

![not_sure_vals](https://user-images.githubusercontent.com/16661213/60869514-17245180-a26a-11e9-8030-5c96bf95b53b.png)

![task_complete_comment](https://user-images.githubusercontent.com/16661213/60872174-370a4400-a26f-11e9-8f29-487cfe68d1d3.png)

In the line 286-287, and the line 290-291, 
if the slot's value is NOT_SURE_VALS(?, don't care, no, ..) return False.
otherwise return True. 

I thought it's too generous to judge that task is success.

For example, when the slot is phone number, the sampled expected answer is 000-0000-0000 (or [phone number identifier]).
But, If my system don't say those NOT_SURE_VALS, every answer is correct. 

Did I misunderstand in some part?
Or, only the 'evaluator mode'(not eval) can measure correctly?
---------------------------------------------------------------------------------------------------------------------

I also checked 'evaluator mode', the core function is "task_success" .
the inner function is "inform_F1"(I just ignored "book_rate" function) 
![task_success_comment](https://user-images.githubusercontent.com/16661213/60876920-c4ea2d00-a277-11e9-9943-2994c8035646.png)
![inform_F1_comment](https://user-images.githubusercontent.com/16661213/60876949-d3d0df80-a277-11e9-84f4-bb60f4e4f2d8.png)

To be success(inform_sess[1] == 1, in task_success function), we should make 'rec' be 1.
it means TP should be > 0, and FN = 0.

So, the core function is "_inform_F1_goal in MultiWozEvaluator".
![inform_F1_goal_comment](https://user-images.githubusercontent.com/16661213/60876983-e5b28280-a277-11e9-86c1-e0b30d1919a9.png)

In line 179-182, The code just said If something in there, return True, otherwise False.
I think same mechanism happen above.

Is it really right way?

**Comment by sungjinl** [comment]
@jeonggwanlee, thanks for your question.

All baselines in the baseline.json are configured to use the evaluator. So please use the evaluator for evaluating your system. 

We will follow up on your question on the evaluator soon.

**Comment by truthless11** [comment]
@jeonggwanlee thanks for your question.

Just as you mentioned, the current evaluation metrics do not check the slot values when evaluating what the system has informed to users. 

However, it is difficult to automatically judge if the informed values are correct or are the ones that the user actually wants. For example, the address of a museum is "Girton college, Huntingdon road" in the database. "Girton college" is also a reasonable answer by only answering a part of the full address. But what if answering a single word "Girton"? Besides, there can be some issues about abbreviation, synonym, typos, etc.

Of course, we are devoting to develop a more strict and sensible judgment on the values. So we will appreciate it if you can give us any suggestions on polishing the evaluation metrics.

**Comment by jeonggwanlee** [comment]
@sungjinl @truthless11  Thank you for your quick reply.

OK, I got it. I'll use evaluator.
now I understood the difficulty of measurement. 
If I have an idea to measure a more strict way, I'll make an issue.

**Comment by jeonggwanlee** [comment]
Thank you for organizing and managing this challenge!
@sungjinl @truthless11 

I had 4 questions.
1. in the "baseline.json", the user simulator side("env") of 4 examples has same components;
NLU(MILU) - UserPolicy(AgendaMultiWoz) - SysPolicy(RuleBased) - NLG(MultiwozTemplateNLG) 
Will you fix those setting in evaluation session? If so, participants can believe their automatic score right (with evaluator)?

2. As I questioned last time, the any string value filling in slot except "?"(question mark) makes success that slot, when the "task_success" function is called. 
But, for natural conversations between system and user, at least the system said correct slot type; for example, "11:00" for [time] slot, not "Hilton hotel", "0123420402" for [phone] slot, not "Hilton hotel".
Will you check those slot type for each slot? (I thought the codes doesn't check this way until now.)

3. In the conversation simulation(user-system), The User informs their situation and constrain the range, like "domain hotel, price range : cheap, area : east". as the normal way, the system should find the hotel satisfying those constraint. It means the system should investigate the database in Multiwoz.
My question is this challenge encourage us to investigate those db("hotel.db", "restaurant.db"..)? (system should fill the satisfying value considering db)
Or, the evaluator discards the constraint so just check the slot type?, or even discards the slot type? 

And I think if we can use "database", there's no confusion about place name. Because the evaluator can grade those value which is in database. So, not allow the synonym, typos, only accept the value in db.

4. Subsequently, In human evaluation phase, will crowd-workers check the slot value which satisfy the constraint(with db)? or just check "appropriateness"

Thank you for reading this issue!
