### ISSUE TITLE
Which Components Should We Develop for DSTC-8 track 1 and How Is a Submission Evaluated?

### ISSUE THREAD

**Issue by wiany11** [ConvLab/ConvLab#31]
I do not know here is the right place to ask such a question. Sorry if I got the wrong place...

We can make so many changes in a system spec. 
For DSTC 8 track 1,  I think we should develop models for `agent/algorithm`, `agent/dst`, and `agent/nlg`. Is it right? Or should we make every change possible to achieve a better score?

I also want to know how a submitted system is evaluated because `env` is not always the same. (`nlu` does not exist in `baseline.json/onenet_rule_dqn_template`.) Which `env` should we assume for evaluation?

Thank you.

**Comment by ConvLab** [comment]
@wiany11  Thanks for your question. For DSTC 8  track 1, you are free to develop and change any modules that you think would boost the performance of the dialogue system, and the system will be evaluated in an end-to-end fashion.  In the submission, you are expected to provide spec json files to run your dialogue, and the evaluation will be made based on your specs.  Hope this makes sense to you.

**Comment by linjian93** [comment]
@ConvLab I met a problem when I submitting the baseline. 

I test `python run.py demo.json milu_rule_rule_template eval` successfully in my localhost. Then I copy the settings of 'milu_rule_rule_template' into the file convlab/spec/submission.json, and change the name 'milu_rule_rule_template' to 'submission1' (As mentioned in point 2 in https://github.com/ConvLab/ConvLab#participation-in-dstc-8). Then nothing else has changed. 

When I submit the zip file, I got a scoring error log "WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.". The score part got nothing at all.

It will be grateful if you help me.

**Comment by jincli** [comment]
@linjian93  CodaLab had a major crash during the last two weeks. Will you try it again so I can check whether we can receive your submission? There is one more thing. We only evaluate your dialogue system at the end of the challenge, so you are not expected to see the score on the fly.  Hopefully this is helpful.

**Comment by linjian93** [comment]
@jincli I have submitted the result yesterday, the result is below.

Num | SCORE | FILENAME | SUBMISSION DATE | STATUS | ✔️
-- | -- | -- | -- | -- | --
1 | --- | ConvLab.zip | 07/22/2019 04:48:26 | Finished |

So how to make sure that my submission is errorless. And how to evaluate my different submitted systems (make sure which submission is better), since you only evaluate it at the end of the challenge.

**Comment by jincli** [comment]
@linjian93  I checked the submission system and can see your submission. You can provide up to 5 specs in your submission.json file, and we will evaluate them as described in http://workshop.colips.org/dstc7/dstc8/DTSC8_multidomain_task_proposal.pdf . To make sure we can run your code and reproduce the results, we highly suggest you using the docker environment and provide your dockerfile if you have made any changes.
