### ISSUE TITLE
How long does it take to release the docs?

### ISSUE THREAD

**Issue by qazwsx74269** [ConvLab/ConvLab#32]

**Comment by qazwsx74269** [comment]
Empty DataFrame
Columns: [epi, t, wall_t, opt_step, frame, fps, total_reward, avg_return, avg_len, avg_success, loss, lr, explore_var, entropy_coef, entropy, grad_norm]
Index: []
Process Process-2:
Traceback (most recent call last):
  File "/home/s50005224/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/s50005224/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/s50005224/ConvLab-master/convlab/experiment/control.py", line 32, in mp_run_session
    metrics = session.run()
  File "/home/s50005224/ConvLab-master/convlab/experiment/control.py", line 146, in run
    metrics = analysis.analyze_session(self.spec, self.agent.body.eval_df, 'eval')
  File "/home/s50005224/ConvLab-master/convlab/experiment/analysis.py", line 175, in analyze_session
    assert len(session_df) > 1, f'Need more than 1 datapoint to calculate metrics'
AssertionError: Need more than 1 datapoint to calculate metrics

when I run `python run.py demo.json sequicity train`, it throws the above error.
My spec setting:
"sequicity": {
    "agent": [{
      "name": "DialogAgent",
      "algorithm": {
        "name": "ExternalPolicy",
        "e2e": {
          "name": "Sequicity",
          "model_file": "https://convlab.blob.core.windows.net/models/Sequicity.zip"
        },
        "action_pdtype": "Argmax",
        "action_policy": "default"
      },
      "memory": {
        "name": "Replay",
        "max_size": 1 
      }
    }],
    "env": [{
      "name": "multiwoz",
      "user_policy": {
        "name": "UserPolicyAgendaMultiWoz"
      },
      "sys_policy": {
        "name": "RuleBasedMultiwozBot"
      },
      "nlu": {
        "name": "OneNetLU",
        "model_file": "https://convlab.blob.core.windows.net/models/onenet.tar.gz"
      },
      "nlg": {
        "name": "MultiwozTemplateNLG",
        "is_user": true
      },
      "evaluator": {
        "name": "MultiWozEvaluator"
      },
      "max_t": 40,
      "max_frame": 1000
    }],
    "body": {
      "product": "outer",
      "num": 2
    },
    "meta": {
      "distributed": false,
      "eval_frequency": 1000,
      "num_eval": 100,
      "max_tick_unit": "total_t",
      "max_trial": 2,
      "max_session": 2,
      "resources": {
        "num_cpus": 0,
        "num_gpus": 1
      }
    }
  },

**Comment by truthless11** [comment]
@qazwsx74269 Sorry for the inconvenience. We are working hard on the docs. Please be patient waiting.

As mentioned in the README, ConvLab can only train the policy component by interacting with a user simulator currently. For other components like Sequicity, ConvLab supports offline supervise learning by  using the **local training script**. Please refer to [Sequicity](https://github.com/ConvLab/ConvLab/tree/master/convlab/modules/e2e/multiwoz/Sequicity) directory for details.
