### ISSUE TITLE
I had questions about database and evaluation.

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#34]
Thank you for organizing and managing this challenge!
@sungjinl @truthless11

I had 4 questions.

1. in the "baseline.json", the user simulator side("env") of 4 examples has same components;
NLU(MILU) - UserPolicy(AgendaMultiWoz) - SysPolicy(RuleBased) - NLG(MultiwozTemplateNLG)
Will you fix those setting in evaluation session? If so, participants can believe their automatic score right (with evaluator)?

2. As I questioned last time, the any string value filling in slot except "?"(question mark) makes success that slot, when the "task_success" function is called.
But, for natural conversations between system and user, at least the system said correct slot type; for example, "11:00" for [time] slot, not "Hilton hotel", "0123420402" for [phone] slot, not "Hilton hotel".
Will you check those slot type for each slot? (I thought the codes doesn't check this way until now.)

3. In the conversation simulation(user-system), The User informs their situation and constrain the range, like "domain hotel, price range : cheap, area : east". as the normal way, the system should find the hotel satisfying those constraint. It means the system should investigate the database in Multiwoz.
My question is this challenge encourage us to investigate those db("hotel.db", "restaurant.db"..)? (system should fill the satisfying value considering db)
Or, the evaluator discards the constraint so just check the slot type?, or even discards the slot type?

And I think if we can use "database", there's no confusion about place name. Because the evaluator can grade those value which is in database. So, not allow the synonym, typos, only accept the value in db.

4. Subsequently, In human evaluation phase, will crowd-workers check the slot value which satisfy the constraint(with db)? or just check "appropriateness"
Thank you for reading this issue!

**Comment by jeonggwanlee** [comment]
Sorry for duplicating issues. (I reopened the previous issue which was closed and made same questions.)
But, I'm worried if the organizer didn't see the previous issue.
If I get answer among them, I'll close the other.

Thanks.

**Comment by truthless11** [comment]
@jeonggwanlee  thanks for your question and suggestion!

Now we examine the slot value based on the slot type in the evaluation metrics, you can refer to pull request #35 for details.

Our metrics do consider the user constraint in the evaluation. "book rate" will check if the selected entity meets the user constraint by evaluating both slot type and slot value.

Though multiwoz dataset encourages the system to search the ontology (database), we should not force the designer to use the slot value in the database. (e.g.  "Girton college" in issue #30 ) We would like to evaluate this in human evaluation.

In terms of fixing components of the user simulator in the evaluation mode, we will revise it sooner or later.
