### ISSUE TITLE
about booking for train

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#37]
Hi, 

I suspected that the function add_sys_da (https://github.com/ConvLab/ConvLab/blob/919d88aecb5d8ee8c167ae1ba5d6589acd1dce19/convlab/evaluator/multiwoz.py#L78) about booking for train.

MultiWozEvaluator monitor booked state using add_sys_da from https://github.com/ConvLab/ConvLab/blob/919d88aecb5d8ee8c167ae1ba5d6589acd1dce19/convlab/evaluator/multiwoz.py#L94 to https://github.com/ConvLab/ConvLab/blob/919d88aecb5d8ee8c167ae1ba5d6589acd1dce19/convlab/evaluator/multiwoz.py#L102.

In line https://github.com/ConvLab/ConvLab/blob/919d88aecb5d8ee8c167ae1ba5d6589acd1dce19/convlab/evaluator/multiwoz.py#L97, 
the condition only handle da == "train-offerbook-ref", not "train-offerbooked-ref".

I understood "train-offerbook" means that the system suggest the user to book, not booked.
and "train-offerbooked" means the system has booked user's ticket.

The reason is, I logged my system and Those are the message. 

Case1-1) (train-offerbook), 
[Syst] tr8464 arrives at 17:43. would you like to book it?
		[SYS_DA] train-inform-id-tr8464
		[SYS_DA] train-inform-arrive-17:43
		[SYS_DA] train-offerbook-none-none

Case1-2) (train-offerbook)
[Syst] i have train tr8842 that will arrive at 07:52. would you like me to book that for you?
		[SYS_DA] train-inform-arrive-07:52
		[SYS_DA] train-inform-id-tr8842
		[SYS_DA] train-offerbook-none-none

Case2-1) (train-offerbooked)
[Syst] i have booked you for the tr8842 train. the total fee is 8.08 gbp payable at the station. your reference number is : r6h3h3h
		[SYS_DA] train-offerbooked-id-tr8842
		[SYS_DA] train-offerbooked-ticket-8.08 gbp
		[SYS_DA] train-inform-ref-r6h3h3h

Case2-2) (train-offerbooked)
[Syst] i have booked 5 tickets for you. the reference number is : zlm0wvqs. is there anything else i can help you with?
		[SYS_DA] train-offerbooked-ref-zlm0wvqs
		[SYS_DA] train-offerbooked-people-5
		[SYS_DA] general-reqmore-none-none

And, I never saw the case "train-offerbook-ref" just in my system. 
If the user simulator need to make those case, the system need to say like below.
"Would you like to book that train which the reference number is 01234567"
=> "train-offerbook-ref-01234567"
Q1. Should my model say like this?

I did the evaluator option (MultiWozEvaluator). 
and user simulator(env) spec in baseline.json is MILU(NLU)-Agenda(UserPolicy)-RuleBased(SysPolicy)-TemplateNLG(NLG).

Q2. Could you add the case of condition "train-offerbook-ref"? (If not, could you say the reason?)

Thank you :)

**Comment by truthless11** [comment]
Thanks @jeonggwanlee . It's fixed now. #38

**Comment by jeonggwanlee** [comment]
Thank you! @truthless11
