### ISSUE TITLE
NLU(MILU) can't understand 'id'(and SpacySplitter can't recognize 'id')

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#39]
Hi,

I found some weird thing. 
Let's see my example.

[User] What 's the train id on that please ?
[Syst] the train id is tr8292 and the price is 16.50 pounds.
................[SYS_DA] train-inform-leave-tr8292
................[SYS_DA] train-inform-ticket-16.50 pounds
[User] Give me the train id , please .
[Syst] the train id is tr8292. would you like me to book it for you?
................[SYS_DA] train-inform-leave-tr8292
................[SYS_DA] train-offerbook-none-none
[User] What 's the train id on that please ?
[Syst] the train id is tr8292. would you like me to book it for you?
................[SYS_DA] train-inform-leave-tr8292
................[SYS_DA] train-offerbook-none-none
[User] What is the train id ?
[Syst] the train id is tr8292. is there anything else i can help you with?
................[SYS_DA] attraction-inform-phone-tr8292
................[SYS_DA] general-reqmore-none-none
[User] Give me the train id , please .
[Syst] the train id is tr8292. is there anything else i can help you with?
................[SYS_DA] attraction-inform-phone-tr8292
................[SYS_DA] general-reqmore-none-none
[User] Could you also give me the train id ?
[Syst] the train id is tr8292. is there anything else i can help you with?
................[SYS_DA] attraction-inform-phone-tr8292
................[SYS_DA] general-reqmore-none-none

User ask system "train id", and my system say 'train id is tr8292' but,
the next turn of User(user simulator) still ask "train id".
As you see, the user simulator understood 'train-inform-leave-tr8292', even it misunderstood '*attraction*-inform-phone-tr8292' 

So I suspected It must be derived from "NLU"(MILU) part.
And I checked that SpacySplitter can't recognize 'id'. (It split 'id' to 'i', 'd').
This is what I tried.
![spacy](https://user-images.githubusercontent.com/16661213/62364875-9e10d500-b55d-11e9-83d5-eddcad90c7dd.png)
it can't recognize 'id', but can only recognize 'ID'.
I think it's quite serious part, because NLU can't understand 'id'

Question. Should the designer consider only 'ID'? not 'id'
 
Thank you.

**Comment by pengbaolin** [comment]
Thanks for pointing out this issue. It is actually triggered by Spacy. I think both ID and id should be considered. I updated the tokenizer by manually adding special cases. It should work now. Thanks.

**Comment by jeonggwanlee** [comment]
@pengbaolin  Thank you for replying and modifying :)
