### ISSUE TITLE
train booking about the number of people

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#40]
Hi,

I found some confusing thing.
This is my system example.

[User] I need 5 tickets .
[Syst] i have booked 5 tickets for you. your reference number is : zlm0jqqt. is there anything else i can help you with?
................[SYS_DA] train-offerbooked-ref-zlm0jqqt
................[SYS_DA] train-offerbooked-people-5
................[SYS_DA] general-reqmore-none-none

But, 
https://github.com/ConvLab/ConvLab/blob/0b38aba96268068e20995ccedf62209a75922fbb/convlab/evaluator/multiwoz.py#L97
there's no 'train-offerbooked-people'.

So, in my system's evaluation phase, there's no booked information.
like this,
{'attraction': None,
 'hospital': None,
 'hotel': None,
 'police': None,
 'restaurant': None,
 'taxi': None,
 'train': None}

Could you add 'train-offerbooked-people'?

Thanks,

**Comment by truthless11** [comment]
Thanks for your question @jeonggwanlee 

The evaluation metrics would detect book intent when there is 'train-offerbooked-ref', so we do not need to add 'train-offerbooked-people'.

The reason why your booked information is empty is that your reference number is wrong.
In the original corpus, the reference number is randomly generated.
However, to make the evaluation available, the reference number is the entity number in the database in ConvLab:
https://github.com/ConvLab/ConvLab/blob/0b38aba96268068e20995ccedf62209a75922fbb/convlab/modules/util/multiwoz/dbquery.py#L61

**Comment by jeonggwanlee** [comment]
I got it. Thank you, and your quick reply!
