### ISSUE TITLE
GBP(Great British Pound) is not acceptable?

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#41]
Hi,

In multiwoz dataset, there appear "GBP(Great British Pound)" in dialog.
But, in https://github.com/ConvLab/ConvLab/blob/0b38aba96268068e20995ccedf62209a75922fbb/convlab/evaluator/multiwoz.py#L213,
only 'pound' or value 'free' is acceptable.

Could you add 'GBP'? or is there any reason being not acceptable?

Thank you.

**Comment by pengbaolin** [comment]
https://github.com/ConvLab/ConvLab/blob/0b38aba96268068e20995ccedf62209a75922fbb/convlab/evaluator/multiwoz.py#L214

'pound' in values is acceptable. So GBP should work as well.

**Comment by jeonggwanlee** [comment]
I'm sorry but I can't understand because when my value is "8.08 gbp",

ex)
key = 'price', value = '8.08 gbp' 

https://github.com/ConvLab/ConvLab/blob/0b38aba96268068e20995ccedf62209a75922fbb/convlab/evaluator/multiwoz.py#L214
elif key == "price" in value or value == "free":
....return 'pound' in value or value == "free"

'pound' in value : False
value == "free" : False

Isn't it right to add " 'gbp' in value " in return part?

**Comment by pengbaolin** [comment]
Got it. In this case, 'gbp' should be added to the return part. We will examine the dataset again and update this part later. Thanks!
