### ISSUE TITLE
about function _check_value 

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#42]
Hi, 

I checked my system's output and, there are some ambiguous issues.
Below is my system's message

[User] Are there any 4 stars available ? It should be a guesthouse type hotel. I ' m looking for a place to stay in the centre part of town .
[Syst] i have two guesthouses in the centre of town. one is cheap and the other is moderately priced. do you have a preference?
        [SYS_DA] hotel-inform-price-moderately priced
        [SYS_DA] hotel-inform-choice-two
        [SYS_DA] hotel-inform-price-cheap
        [SYS_DA] hotel-inform-area-centre of town 
        [SYS_DA] hotel-inform-type-guesthouses
        [SYS_DA] hotel-inform-choice-other
        [SYS_DA] hotel-select-none-none

[SYS_DA] is printed at the function "add_sys_da" in evaluator/multiwoz.py and this is what user simulator NLU(my case, MILU) understood.

MILU can't parse "moderately priced" into "moderate" in price case, but also parse "centre of town" into "centre".
The problem is when inform_F1 and _check_value is invoked, 
https://github.com/ConvLab/ConvLab/blob/0b38aba96268068e20995ccedf62209a75922fbb/convlab/evaluator/multiwoz.py#L199
_check_value return "False", because it only allows "moderate" and "centre" (not moderately priced and centre of town).

I think they are correct. Could you allow those case?

Code suggestion is like,
elif key == "pricerange":
....for candidate in ["cheap", "expensive", "moderate", "free"]:
........if candidate in value:
............return True
....return False   
The "area" case also be changed same way.

Thank you.

**Comment by jincli** [comment]
@jeonggwanlee  Thanks for raising the issue! The code change you suggested definitely works in your examples, but pure sub-string match has the risk of mismatching when 'value' is a more complicated string.  The existing (NLU) models are the baselines we provide for your convenience, and have their own limitations. We highly encourages users building your model and contribute to ConvLab. Hope this resolves your question. Thanks.

**Comment by jeonggwanlee** [comment]
Thank you for replying! @jincli
I got that risk...!

I participated in the DSTC8 Track 1 actually.
In that challenge, can the designer modify the user simulator part? because there's limitation from user simulator part. So if the designer can change the user simulator part, they can accomplish better success rate.

But, To evaluate all participants model conveniently, it's normal to fix the user simulator part, isn't it?

**Comment by jincli** [comment]
@jeonggwanlee  Our final evaluations consist of end2end evaluation based on the existing user simulator and human evaluation. If you change your user simulator, it might affect your final end2end evaluation. Surely, if your suggestion of user simulator change is good enough, it might help increase the performance in human evaluation. Please let us know how you would like to do the change (maybe send a PR), and we will consider it in our future release.

**Comment by jeonggwanlee** [comment]
@jincli Thank you for replying!
Until now, I have not tried to change the user simulator part. If I have some idea, I make suggestion in this github page.
