### ISSUE TITLE
NLU(MILU) can't recognize "free internet"?

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#43]
Hi, 

I found that MILU can't regognize "internet is available or not"

Let's see my example.

ex 1)
[User] I am looking for a particular hotel . its name is called kirkwood house.
[Syst] the kirkwood house is a guesthouse in the north area. it is moderately priced and has 4 stars. would you like me to book it for you?
        [SYS_DA] hotel-inform-stars-4
        [SYS_DA] hotel-inform-area-north
        [SYS_DA] hotel-inform-price-moderately priced
        [SYS_DA] hotel-inform-name-the kirkwood house
        [SYS_DA] hotel-inform-type-guesthouse
        [SYS_DA] booking-inform-none-none
[User] Does it have internet ?
[Syst] yes it has internet.
        [SYS_DA] hotel-inform-internet-none

ex 2)
[User] Does it have internet ? I do n't need it booked but what s the address ? What type of hotel is it ?
[Syst] dojo noodle bar is a guesthouse. the address is 40210 millers yard city centre.
        [SYS_DA] restaurant-inform-name-dojo noodle bar
        [SYS_DA] restaurant-inform-addr-40210 millers yard city centre
        [SYS_DA] hotel-inform-type-guesthouse
[User] Can you tell me if the hotel has internet available ? Could i get their address ?
[Syst] yes, it has internet. the address is 40210 millers yard, chesterton.
        [SYS_DA] hotel-inform-addr-chesterton
        [SYS_DA] hotel-inform-addr-40210 millers yard
[User] No , i just need to know if they have free internet .
[Syst] they do have free internet.
        [SYS_DA] hotel-inform-internet-none

ex 3)
[User] I need a place to stay in the don't care please .
[Syst] i have many options available. is there a price range you prefer?
        [SYS_DA] hotel-inform-choice-many
        [SYS_DA] hotel-request-price-?
[User] How many stars ? No , i just need to know if they have free internet . I just need the postcode .
[Syst] the acorn guest house has internet. the postcode is cb41da.
        [SYS_DA] hotel-inform-post-cb41da
        [SYS_DA] hotel-inform-name-the acorn guest house
        [SYS_DA] hotel-inform-internet-none

I also manually tried MILU can parse "free internet" sentence.
I made wifi_sentence_list like this.
wifi_list = ["this hotel has free wifi", "it has free wifi", "it has free internet", "it includes internet",\
                         "they has free internet", "it serve free internet", "hotel has free wifi", "this hotel has free internet"]
and only the case "this hotel has free wifi" => {''Hotel-Inform", [['Internet', 'yes']]}

To guarantee my experiment, I captured my result.
![internet_capture](https://user-images.githubusercontent.com/16661213/62425242-fb4e8700-b713-11e9-861a-3ed19a25436a.png)

Can't we overcome those MILU's limitation?

Thank you.

**Comment by pengbaolin** [comment]
Thanks for raising this issue. We provided several NLU models to help users quickly set up a whole dialogue pipeline.  It is possible that current NLU models might not be possible to accurately recognize all the intents. (That's also why jointly training and/or DM optimization are necessary. ) 

Users are free and highly encouraged to build up their models to overcome existing errors. :)

**Comment by jeonggwanlee** [comment]
Thank you for replying! @pengbaolin 

I didn't mention why system setting.
I didn't use MILU in my system part(agent part), only use user simulator part(MILU-AgendaPolicy-TemplateNLG), same as baseline.json.

Can we change the user simulator part?
I guessed we can't modify the user simulator components(MILU-AgendaPolicy-TemplateNLG), isn't it?
