### ISSUE TITLE
No file in data/glove?

### ISSUE THREAD

**Issue by fanghy06** [ConvLab/ConvLab#45]
Hi! 
I am training the Sequicity model (one of the e2e models).
![image](https://user-images.githubusercontent.com/52768013/62529095-8e9ccf00-b870-11e9-88cb-7937e4d29842.png)
I download the given data. 

![image](https://user-images.githubusercontent.com/52768013/62529589-82fdd800-b871-11e9-80c1-095b926dbbb8.png)

But when I run:  python model.py -mode train -model tsdf-multiwoz
There is a FileNotFoundError: [Errno 2] No such file or directory: '/convlab/ConvLab/convlab/modules/e2e/multiwoz/Sequicity/data/glove/glove.6B.50d.txt'
So, should there be a txt file in the folder?
Thank you!

**Comment by pengbaolin** [comment]
Thanks for pointing out. There should be such a file in data folder. 

Please download the embedding file at https://nlp.stanford.edu/projects/glove/, and then move it to /convlab/ConvLab/convlab/modules/e2e/multiwoz/Sequicity/data/glove
