### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#46]
Hi, 
I have 3 questions.
In the human evaluation phase, What is the criteria to evaluate participant's model?
I have already read in the task proposal pdf(http://workshop.colips.org/dstc7/dstc8/DTSC8_multidomain_task_proposal.pdf).
For task1, "Crowsworker-based evaluation" is given.
For task2(meta-learning task), they wrote "Human annotators will be asked to judge the appropriateness, informativeness and utility of the responses".

Q1) Could you explain more detail about human evaluation of task1? (Will the same measurement in task2(appropriateness, informativeness, and utility of the responses) be applied?)

Q2) I also wonder how crowdworkers work in real. one is interacting with participant's model (such crowdworkers play a role as user) and judging(appropriateness, informativeness, and utility of the responses). the other is the conversation with user simulator is given, then crowdworkers read the conversation with user simulator and judging since the automatic measurement and user simulator is not perfect.(NLU part sometimes failed to understand model's intent, so crowdworkers revise it).

Q3) What kind of autometric measurement will be used? When I run with "evaluator" mode, I got return(average reward), success rate, average turns, P(precision), R(Recall), F1 score.(6 metrics)
But, in previous, I saw only three measurements(average reward, success rate, average turns) in CodaLab DSTC8 page.(https://competitions.codalab.org/competitions/20162#learn_the_details-overview) (now those explanation disappeared. That's why I ask). Until now, Will the participant's model be evaluated using those 6 metric right?

Thank you!

**Comment by jincli** [comment]
@jeonggwanlee  Thanks for your questions. The participants will be evaluated using 6 metrics for automatic evaluation. CodaLab had a major crash several weeks ago, and we recreated the page for the competition after that. Thus, the current CodaLab page might not contain exactly the same information as before. As for human evaluation, crow-workers will interact with participants' models and provide ratings.

**Comment by jeonggwanlee** [comment]
@jincli Thank you for replying.
Your response helped me to understand.
