### ISSUE TITLE
Some problems on evaluator(MILU NLU)

### ISSUE THREAD

**Issue by DH95** [ConvLab/ConvLab#54]
Hi, while evaluating our model, I noticed something strange in the evaluator.

1. Goal: {'restaurant': {'info': {'food': 'italian', 'pricerange': 'moderate', 'area': 'east'}, 'reqt': {'address': '?', 'postcode': '?'}, 'fail_info': {'food': 'italian', 'pricerange': 'expensive', 'area': 'east'}}, 'hotel': {'info': {'type': 'guesthouse', 'parking': 'yes', 'pricerange': 'moderate', 'area': 'north'}, 'reqt': {'stars': '?', 'address': '?'}}, 'taxi': {'info': {'leaveAt': '03:30'}, 'reqt': {'car type': '?', 'phone': '?'}}}

the goal of this episode is requesting the address of moderate price italian restaurant in east. But, 
User utterance: I am looking for a expensive restaurant in the **center of the city** . I would prefer italian food please . I would prefer it in the **east area** .

the generated user utterance contains two area keywords, center of the city and east area. In this case, our dialog system find wrong db search results. 

2. 
Goal: {'restaurant': {'info': {'food': 'british', 'pricerange': 'moderate', 'area': 'centre'}, 'book': {'day': 'sunday', 'time': '16:30', 'people': '8'}, 'booked': '?'}, **'hotel': {'info': {'parking': 'yes', 'pricerange': 'moderate'}, 'reqt': {'postcode': '?'}, 'book': {'stay': '2', 'people': '8', 'day': 'sunday'}, 'booked': '?'**}}

[2019-08-21 20:38:59,466 PID:46413 NL logger.py nl] User utterance: Actually , can you give me the postcode for that ?
[2019-08-21 20:38:59,466 PID:46413 ACT logger.py act] Inferred user action: Actually , can you give me the postcode for that ?
[2019-08-21 20:38:59,466 PID:46413 STATE logger.py state] Dialog state: Actually , can you give me the postcode for that ?
[2019-08-21 20:39:00,699 PID:46413 ACT logger.py act] System action: the postcode is cb21ab.
[2019-08-21 20:39:00,699 PID:46413 NL logger.py nl] System utterance: the postcode is cb21ab.
[2019-08-21 20:39:00,718 PID:46413 ACT logger.py act] Inferred system action: {'Restaurant-Inform': [['Post', 'cb21ab']]}
[2019-08-21 20:39:00,718 PID:46413 NL logger.py nl] User utterance: And i need a postcode .
[2019-08-21 20:39:00,718 PID:46413 ACT logger.py act] Inferred user action: And i need a postcode .
[2019-08-21 20:39:00,718 PID:46413 STATE logger.py state] Dialog state: And i need a postcode .
[2019-08-21 20:39:03,112 PID:46413 ACT logger.py act] System action: the postcode is cb21ab.
[2019-08-21 20:39:03,112 PID:46413 NL logger.py nl] System utterance: the postcode is cb21ab.
[2019-08-21 20:39:03,125 PID:46413 ACT logger.py act] Inferred system action: {'Restaurant-Inform': [['Post', 'cb21ab']]}
[2019-08-21 20:39:03,125 PID:46413 NL logger.py nl] User utterance: That sounds fine , i just need the postcode though .
[2019-08-21 20:39:03,125 PID:46413 ACT logger.py act] Inferred user action: That sounds fine , i just need the postcode though .
[2019-08-21 20:39:03,125 PID:46413 STATE logger.py state] Dialog state: That sounds fine , i just need the postcode though .
{'food': 'british', 'pricerange': 'moderate', 'name': 'not mentioned', 'area': 'centre'}
[2019-08-21 20:39:04,374 PID:46413 ACT logger.py act] System action: the postcode is cb21ab.
[2019-08-21 20:39:04,374 PID:46413 NL logger.py nl] System utterance: the postcode is cb21ab.
[2019-08-21 20:39:04,389 PID:46413 ACT logger.py act] Inferred system action: {'Restaurant-Inform': [['Post', 'cb21ab']]}
[2019-08-21 20:39:04,389 PID:46413 NL logger.py nl] User utterance: Can i get the postcode for both of them ?
[2019-08-21 20:39:04,390 PID:46413 ACT logger.py act] Inferred user action: Can i get the postcode for both of them ?
[2019-08-21 20:39:04,390 PID:46413 STATE logger.py state] Dialog state: Can i get the postcode for both of them ?

Sometimes evaluator repeats same utterance over and over although our system give correct response and MILU correctly detect it's slot and value . Also, this task fail because it has goal 'hotel' but user didn't ask about any information about the hotel. What's the problem ?

3. this episode is related to police domain.
Goal: {'police': {'info': {}, 'reqt': {'address': '?', 'phone': '?'}}}

[2019-08-21 20:43:05,742 PID:46413 ACT logger.py act] Inferred user action: Can you give me the phone number please ? Also , can you give me the exact address to the station ?
[2019-08-21 20:43:05,742 PID:46413 STATE logger.py state] Dialog state: Can you give me the phone number please ? Also , can you give me the exact address to the station ?
[2019-08-21 20:43:06,065 PID:46413 ACT logger.py act] System action: the address is parkside, cambridge.
[2019-08-21 20:43:06,065 PID:46413 NL logger.py nl] System utterance: the address is parkside, cambridge.
[2019-08-21 20:43:06,092 PID:46413 ACT logger.py act] Inferred system action: {}

MILU NLU cannot detect any information related to police and hospital domain. Do you have an update plan for this problem?

4. Should I consider when a user requests information that is not in db? (NoOffer, NoBook case)

thank you.

**Comment by jincli** [comment]
@DH95  Thanks for raising the questions! We are looking into the issues, and will keep you informed once the issues are resolved. For the final evaluation, you only need to consider user requests in the db.

**Comment by DH95** [comment]
Thank you for answering my question! I found one more thing, 
User action: {'Restaurant-Inform': [['Food', 'modern european'], ['Price', 'moderate'], ['Area', 'west']]}
In this case, there is no restaurant in db that meets these conditions.

**Comment by truthless11** [comment]
> Thank you for answering my question! I found one more thing,
> User action: {'Restaurant-Inform': [['Food', 'modern european'], ['Price', 'moderate'], ['Area', 'west']]}
> In this case, there is no restaurant in db that meets these conditions.

@DH95 Could you show us the complete log of that session?

**Comment by DH95** [comment]
[36m[2019-08-22 23:39:27,001 PID:98273 ACT logger.py act][0m User action: {'Restaurant-Inform': **[['Food', 'modern european'], ['Price', 'moderate'], ['Area', 'west']]**}[0m
[36m[2019-08-22 23:39:27,001 PID:98273 ACT logger.py act][0m Goal: {'restaurant': {'info': {'food': 'italian', 'pricerange': 'moderate', 'area': 'west'}, 'reqt': {'address': '?'}, 'book': {'time': '11:45', 'day': 'saturday', 'people': '4'}, 'fail_book': {'time': '12:45', 'day': 'saturday', 'people': '4'}, 'fail_info': {'food': 'modern european', 'pricerange': 'moderate', 'area': 'west'}, 'booked': '?'}, 'train': {'info': {'destination': 'kings lynn', 'day': 'monday', 'departure': 'cambridge', 'leaveAt': '18:00'}, 'reqt': {'duration': '?'}}}[0m
[36m[2019-08-22 23:39:27,001 PID:98273 NL logger.py nl][0m User utterance: Are there any modern european restaurants in the center of town ? I also need a place to dine that is moderate priced . Can you help me find a restaurant ? i want to find a place in the west .[0m
[36m[2019-08-22 23:39:27,001 PID:98273 ACT logger.py act][0m Inferred user action: Are there any modern european restaurants in the center of town ? I also need a place to dine that is moderate priced . Can you help me find a restaurant ? i want to find a place in the west .[0m
[36m[2019-08-22 23:39:27,002 PID:98273 STATE logger.py state][0m Dialog state: Are there any modern european restaurants in the **center of town ?** I also need a place to dine that is moderate priced . Can you help me find a restaurant ? i want to find a **place in the west** .[0m
[36m[2019-08-22 23:39:27,770 PID:98273 ACT logger.py act][0m System action: de luca cucina and bar is in the centre and in the moderate price range. would you like me to book a table for you?[0m
[36m[2019-08-22 23:39:27,770 PID:98273 NL logger.py nl][0m System utterance: de luca cucina and bar is in the centre and in the moderate price range. would you like me to book a table for you?[0m
[36m[2019-08-22 23:39:27,805 PID:98273 ACT logger.py act][0m Inferred system action: {'Restaurant-Inform': [['Price', 'moderate'], ['Area', 'centre'], ['Name', 'de luca cucina and bar']], 'Booking-Inform': [['none', 'none']]}[0m
[36m[2019-08-22 23:39:27,805 PID:98273 NL logger.py nl][0m User utterance: Is that located in the west ?[0m
[36m[2019-08-22 23:39:27,806 PID:98273 ACT logger.py act][0m Inferred user action: Is that located in the west ?[0m
[36m[2019-08-22 23:39:27,806 PID:98273 STATE logger.py state][0m Dialog state: Is that located in the west ?[0m
[36m[2019-08-22 23:39:28,182 PID:98273 ACT logger.py act][0m System action: yes, that is located in the centre.[0m
[36m[2019-08-22 23:39:28,182 PID:98273 NL logger.py nl][0m System utterance: yes, that is located in the centre.[0m
[36m[2019-08-22 23:39:28,211 PID:98273 ACT logger.py act][0m Inferred system action: {'Attraction-Inform': [['Area', 'centre']]}[0m
[36m[2019-08-22 23:39:28,212 PID:98273 NL logger.py nl][0m User utterance: May i also get the address for the restaurant ?[0m
[36m[2019-08-22 23:39:28,212 PID:98273 ACT logger.py act][0m Inferred user action: May i also get the address for the restaurant ?[0m
[36m[2019-08-22 23:39:28,212 PID:98273 STATE logger.py state][0m Dialog state: May i also get the address for the restaurant ?[0m
[36m[2019-08-22 23:39:28,903 PID:98273 ACT logger.py act][0m System action: the address is 83 regent street, postcode cb21aw. is there anything else i can help you with?[0m
[36m[2019-08-22 23:39:28,903 PID:98273 NL logger.py nl][0m System utterance: the address is 83 regent street, postcode cb21aw. is there anything else i can help you with?[0m
[36m[2019-08-22 23:39:28,929 PID:98273 ACT logger.py act][0m Inferred system action: {'Restaurant-Inform': [['Post', 'cb21aw'], ['Addr', '83 regent street']], 'general-reqmore': [['none', 'none']]}[0m
[36m[2019-08-22 23:39:28,930 PID:98273 NL logger.py nl][0m User utterance: Can you book me a table for 4 ? I 'll be needing a table for saturday . Can you try to book it at 12:45 .[0m
[36m[2019-08-22 23:39:28,930 PID:98273 ACT logger.py act][0m Inferred user action: Can you book me a table for 4 ? I 'll be needing a table for saturday . Can you try to book it at 12:45 .[0m
[36m[2019-08-22 23:39:28,930 PID:98273 STATE logger.py state][0m Dialog state: Can you book me a table for 4 ? I 'll be needing a table for saturday . Can you try to book it at 12:45 .[0m
[36m[2019-08-22 23:39:29,565 PID:98273 ACT logger.py act][0m System action: booking was successful. the table will be reserved for 15 minutes. 
 reference number is : 00000016.[0m
[36m[2019-08-22 23:39:29,565 PID:98273 NL logger.py nl][0m System utterance: booking was successful. the table will be reserved for 15 minutes. 
 reference number is : 00000016.[0m
[36m[2019-08-22 23:39:29,598 PID:98273 ACT logger.py act][0m Inferred system action: {'Booking-Book': [['Ref', '00000016']]}[0m
[36m[2019-08-22 23:39:29,598 PID:98273 NL logger.py nl][0m User utterance: Thank you that will be all for now .[0m
[36m[2019-08-22 23:39:29,598 PID:98273 ACT logger.py act][0m Inferred user action: Thank you that will be all for now .[0m
[36m[2019-08-22 23:39:29,598 PID:98273 STATE logger.py state][0m Dialog state: Thank you that will be all for now .[0m
[36m[2019-08-22 23:39:30,132 PID:98273 ACT logger.py act][0m System action: you're welcome. have a great day![0m
[36m[2019-08-22 23:39:30,132 PID:98273 NL logger.py nl][0m System utterance: you're welcome. have a great day![0m
[36m[2019-08-22 23:39:30,156 PID:98273 ACT logger.py act][0m Inferred system action: {'general-bye': [['none', 'none']], 'general-welcome': [['none', 'none']]}[0m

this episode contains 3 problems:
1. the restaurant that satisfy ['Food', 'modern european'], ['Price', 'moderate'], ['Area', 'west'] is not in the restaurant_db.json

2. Goal of this episode is to find the italian restaurant, but the user asks about a modern European restaurant.

3. Two different area information (center of the town, in the west) appears twice in a user utterance .

**Comment by truthless11** [comment]
@DH95 Multiwoz corpus encourages goal changes when they collect the data. Refer to the subsection 3.1 Dialogue Task:

> With a certain probability, the initial constraints of a task may be set to values so that no matching database entry exists.

As seen in this case, the user goal contains a failed constraint `'fail_info': {'food': 'modern european', 'pricerange': 'moderate', 'area': 'west'}`. The implemented Agenda user simulator will first ask about the failed constraint. After the simulator is told that the initial request does not exist, then it continues to inquire about an existed constraint `'info': {'food': 'italian', 'pricerange': 'moderate', 'area': 'west'}`.

The final evaluation will only consider the existed constraint in the DB, which is `info` here, but this does not mean that you don't need to consider a user request that is not in DB. The designed system is encouraged to use `Nooffer` or `Nobook` to address this situation and then lead the user simulator to tell the existed constraint.

BTW, we are working hard to debug the NLG issue (two different area info) and MILU NLU issue (fail to detect police domain), plz be patient as this may take some time.

**Comment by DH95** [comment]
@truthless11 I appreciate your taking the time to answer my questions.Considering what you said, I'll reflect it in our model.
Thank you!

**Comment by truthless11** [comment]
NLG issue fixed. #55

**Comment by jincli** [comment]
@DH95  Will you try again with the updated milu model https://convlab.blob.core.windows.net/models/milu.tar.gz ? Thanks.
