### ISSUE TITLE
About the tagging of training data

### ISSUE THREAD

**Issue by DarrenZhu1103** [ConvLab/ConvLab#59]
Q1:
We found that in the training data, about 1/4 of the dialog_act lacks the "Name" slot and about 1/3 of the dialog_act lacks the "Ref" slot when they are actually in the raw sentence.
For example the data 
"text": "Actually , could I have the phone number of Cote ?"
"dialog_act": {"Restaurant-Request": [["Phone", "?"]]}
lacks the "Name" slot and the data
"text": "That sounds perfect , please book 1 ticket for me , and can I have the reference number ?"
"Train-Inform": [["People", "1"]]}
lacks the "Ref" slot.

Q2:
What is the configuration of GPU and other resources when evaluating?

**Comment by zqwerty** [comment]
Thanks for the questions.
For Q1, how do you estimate the fraction of samples that miss some annotation? Could you give more examples? Since we use rules to annotate user dialog act ([code](https://github.com/ConvLab/ConvLab/blob/master/data/multiwoz/annotation/annotate.py)), some error is inevitable. We will modify annotation if necessary.

For the `Name` slot, we can add a rule to match the name of entities in the database. But I think the situation is rare.
For the `Ref` slot, I think this only happens for Train domain sometimes and have been fixed right now. But we have not updated data yet.

If the problem is really serious, we will update the annotation.

**Comment by DarrenZhu1103** [comment]
We tried to match the name of entities in the database with all the texts and we got  the fraction of samples that miss "Name" and "Ref" slots or have mistakes with these slots.
Besides that, there are about 6769 blank dialog_act.
There are some examples.
In dialogue PMUL4643:
"text": "I would like to book the Ashley Hotel for 5 people for 2 nights ."
"dialog_act": {"Hotel-Inform": [["Type", "Hotel"], ["Stay", "2"], ["People", "5"]]}
lacks Name:Ashley Hotel.

In dialogue PMUL1702:
"text": "Can you also look up the hotel Carolina Bed and breakfast ?"
"dialog_act": {"Hotel-Inform": [["Name", "Carolina Bed"]]}
has a mistake, the value of the "Name" slot should be Carolina Bed and breakfast.

In dialogue PMUL3207:
"text": "I would suggest the acorn guest house ."
"dialog_act": {"Hotel-Recommend": [["Name", "the acorn guest house"]]}
has a mistake, the value of the "Name" slot should be acorn guest house.

In dialogue PMUL4475:
"text": "You have your choice of Hakka or The Hotpot , in luxury options , or the moderately priced Golden Wok ."
"dialog_act": {"Restaurant-Select": [["Name", "Hakka or The Hotpot"], ["Name", "Golden Wok"], ["Price", "luxury options"], ["Price", "or the moderately priced"]]}
has a mistake, the "Name" slot should be [["Name", "Hakka"], ["Name", "The Hotpot"], ["Name", "Golden Wok"]]

**Comment by zqwerty** [comment]
Thanks!

The first two examples are from user side (our annotation), the others are from system (original annotation). We add a patch annotation [script](https://github.com/ConvLab/ConvLab/blob/master/data/multiwoz/annotation/annotate_patch_name.py). You can use the script to annotate both user side and system side `Name` slot.

**Notice**: Not update data now.

**Comment by DarrenZhu1103** [comment]
Thanks for the answer!

But we still have 3 problems.

Q1:
In the final simulation-based evaluation phase, how will the model be evaluated? Is the nlu and nlg part in user-simulator fixed?

Q2:
What is the configuration of GPU and other resources when evaluating? Can we use some complex models?

Q3:
We still found some mistakes in the data. More than 10% of the `Type` and `Leave` slots are missing and more than 10% of the `Ticket` slots in the `Train-Request` should be removed.
Here are some examples.
**1.Type**
```shell
PMUL4338
  {
    "text": "I 'm looking to stay at a 4 star hotel that includes free parking .",
    "metadata": {},
    "dialog_act": {
     "Hotel-Inform": [
      [
       "Parking",
       "yes"
      ],
      [
       "Stars",
       "4"
      ]
     ]
    },
    "span_info": [
     [
      "Hotel-Inform",
      "Stars",
      "4",
      7,
      7
     ]
    ]
   }
```
> miss Type: hotel


MUL1155
```shell
   {
    "text": "I also need to book a guesthouse in the north .",
    "metadata": {},
    "dialog_act": {
     "Hotel-Inform": [
      [
       "Area",
       "north"
      ]
     ]
    },
    "span_info": [
     [
      "Hotel-Inform",
      "Area",
      "north",
      9,
      9
     ]
    ]
   }
```
> miss Type: guesthouse

PMUL1466
```shell
   {
    "text": "I want to go to a theater in the east part of town . Can you help me find some ?",
    "metadata": {},
    "dialog_act": {
     "Attraction-Inform": [
      [
       "Area",
       "east"
      ]
     ]
    },
    "span_info": [
     [
      "Attraction-Inform",
      "Area",
      "east",
      9,
      9
     ]
    ]
   }
```
> miss Type: theater

**2.Leave**

SNG01642
```shell
   {
    "text": "Yes , I will be leaving at 16:30 from Bedouin .",
    "metadata": {},
    "dialog_act": {
     "Taxi-Inform": [
      [
       "Depart",
       "Bedouin"
      ]
     ]
    },
    "span_info": [
     [
      "Taxi-Inform",
      "Depart",
      "bedouin",
      9,
      9
     ]
    ]
   }
```
> miss Leave:16:30

**3.Ticket**

MUL2197
```shell
   {
    "text": "No preference really . Could you pick one and get me the postcode and price range please ?",
    "metadata": {},
    "dialog_act": {
     "Hotel-Request": [
      [
       "Price",
       "?"
      ],
      [
       "Post",
       "?"
      ]
     ],
     "Train-Request": [
      [
       "Ticket",
       "?"
      ]
     ]
    },
    "span_info": []
   }
```
> "Train-Request": [...] should be removed

PMUL1960
```shell
   {
    "text": "I do n't care about price range , actually .",
    "metadata": {},
    "dialog_act": {
     "Train-Request": [
      [
       "Ticket",
       "?"
      ]
     ]
    },
    "span_info": []
   }
```
> "Train-Request": [...] should be removed

**Comment by pengbaolin** [comment]
A1: The submission will be evaluated with milu_rule_[AGENT]_template. The NLU and NLG are part of user simulator and are fixed. As reflected in the template name, we will use milu for NLU and template method for NLG. As such, participants are not necessary to provide such models for simulator but could in agent part.

A2: Yes, you can use complex models. We will probably use machines for evaluation with > 1 P100 GPU and 128GB memory. 

A3: Right, the annotation of multiwoz indeed has errors. Refer to https://arxiv.org/abs/1907.01669.

**Comment by DarrenZhu1103** [comment]
Thanks!

And will you update the data with `MULTIWOZ2.1`?
Will the final test data set also be updated?

**Comment by pengbaolin** [comment]
Updating the data will affect NLU models. We only use that model in user simulator to screen bad submissions. The final ranking is still based on human evaluation. So I think the influence of updating the data is weak.

We will keep the setups as it is now. But participants can use whatever kind of data to train their own NLU and NLG.
