### ISSUE TITLE
About time(arriveBy, leaveAt) of train case

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#61]
Hello!

I found a strange part when simulating user simulator.
I used "milu-agenda-template"

Let's see my example.
<pre><code>-----Goal-----
{
    "train": {
        "info": {
            "destination": "cambridge",
            "day": "thursday",
            "arriveBy": "17:15",
            "departure": "cambridge"
        },
        "reqt": {
            "leaveAt": "?",
            "price": "?"
        },
        "book": {
            "people": "5"
        },
        "booked": "?"
    },
    "restaurant": {
        "info": {
            "pricerange": "cheap"
        },
        "reqt": {
            "address": "?"
        }
    }
}
-----Goal-----

[User] I need to travel on thursday .
[Syst] Where are you departing from and going to?
[User] Yes I would like to go to cambridge please . Great I also need a train departs from cambridge .
[Syst] What time would you like to leave?
***[User] I need it to arrive by 17:15 .***
[Syst] TR4526 arrives at 17:09. Would you like me to book it for you?
\ \ \ \ Inferred system action : {'Train-Inform': [['Arrive', '17:09'], ['Id', 'TR4526']], 'Train-OfferBook': [['none', 'none']]} (This is from logger.act('Inferred system action : {self.get_sys_act()}'))
***[User] I need it to arrive by 17:15 .***
</pre></code>

As you see, the user simulator repeated same utterance, 
and MILU can understand 17:09 as arrive time.(Inferred system action)
I followed steps of how user simulator(MILU-PolicyAgenda) works.

[policy.predict]
https://github.com/ConvLab/ConvLab/blob/74cfda261babccc22038a1107033a38029636039/convlab/modules/usr/user.py#L44

[agenda.update]
https://github.com/ConvLab/ConvLab/blob/74cfda261babccc22038a1107033a38029636039/convlab/modules/policy/user/multiwoz/policy_agenda_multiwoz.py#L101

[update_domain] diaact='train-inform', slot_vals=[['arriveBy','17:09''],['trainID','TR4526']]
https://github.com/ConvLab/ConvLab/blob/74cfda261babccc22038a1107033a38029636039/convlab/modules/policy/user/multiwoz/policy_agenda_multiwoz.py#L384

I think this line can't cover our case.
https://github.com/ConvLab/ConvLab/blob/74cfda261babccc22038a1107033a38029636039/convlab/modules/policy/user/multiwoz/policy_agenda_multiwoz.py#L437
[if condition part] is,
slot : 'arriveBy', value : '17:09'
len(g_fail_info) <= 0 : True
slot in g_info : True
value != g_info[slot] : True (17:09 v.s. 17:15)

It means the simulator only accepts "17:15", not earlier than "17:15" 
(Normally, when the train arrive earlier than expected, It tolerates, reversely,
when the train depart later than expected, It tolerates. 
and the query function(dbquery.py) and _book_rate_goal also follow this rule.)
Also, there's no train satisfying 17:15 with previous constraints (arrive cambridge, depart cambridge.) therefore, my model can just recommend the earlier, but most closest train (from train database).

If this closest time recommendation is not tolerated, my model should say there's no train matching with your requirement. (but there's still a problem, because the time slot is in "info", not "book" or "fail_book".)

Is there any opinion for this circumstance?

I captured my case to see easily.
![screenshot](https://user-images.githubusercontent.com/16661213/63870241-8b6eac00-c9f4-11e9-903b-b3f91b173630.png)
the process after this is, it push the unsatisfying slot-value('arriveBy', '17:15') and the user utterance is repeated.

Thank you for reading my messy issue!

**Comment by jeonggwanlee** [comment]
There is a similar case.

<pre><code>[Syst] TR8724 leaves at 13:16. Would you like me to book it?
        [SYS_DA] : train-inform-leave-13:16
        [SYS_DA] : train-inform-id-tr8724
        [SYS_DA] : train-offerbook-none-none

[User] I need a train leaving after 13:15 .
        [USR_DA] : train-inform-leave-13:15

[Syst] TR8724 leaves at 13:16. Would you like me to book it?
        [SYS_DA] : train-inform-leave-13:16
        [SYS_DA] : train-inform-id-tr8724
        [SYS_DA] : train-offerbook-none-none

[User] Yes , I need to leave sometimes after 13:15 .
        [USR_DA] : train-inform-leave-13:15
</pre></code>

**Comment by truthless11** [comment]
@jeonggwanlee Thanks for reporting the issue. Now it's fixed. #62
