### ISSUE TITLE
Bug in MILU NLU training/dataset reader

### ISSUE THREAD

**Issue by xylankant** [ConvLab/ConvLab#74]
Hello,

We think we found some quite serious issues in 
 `ConvLab/convlab/modules/nlu/multiwoz/milu/dataset_reader.py`, when training individual NLUs for agent and user.

1) Both lines 77 and 88 use variable `i` to enumerate over data (turns in the dialogue, and tokens in a turn, respectively). The scope of the loop in line 88 effectively overrides the variable used in line 77.

2) As an effect of this(?), lines 122 and 124 seems to have their tests for user vs. agent turn switched, and call the `continue` statement on the wrong turns
`if self._agent and self._agent == "user" and i % 2 != 1: `
`    continue`
will continue on turns that are even (0, 2 , 4), even though those turns (in the data) are the user turns. Vice-versa for agent.

3) As an effect of (1), it seems like the `i` referred to in lines 122 and 124 are actually equal to the number of tokens of the current turn, instead of the ID/counter of the current turn. (Thus it is basically random...)

These issues effectively render training user- and agent-specific models using the system.jsonnet /user.jsonnet configurations useless, as the training is not done with the proper system or user turns.

4) Regardless of the above, it seems strange to have the turn-number check at the end of the turn loop, instead of the beginning. Right now, a whole lot of processing is carried out, before it is simply "thrown away" due to the continue statements toward the end.

Please let us know if our observations here are wrong/if we have overlooked anything, but it seems like at the moment, agent- and user-specific MILU training is broken.

Cheers,
Philip

**Comment by jincli** [comment]
@xylankant  thanks for raising this up! Please check this PR: https://github.com/ConvLab/ConvLab/pull/75
