### ISSUE TITLE
maximum limit of submission file in codalab

### ISSUE THREAD

**Issue by jeonggwanlee** [ConvLab/ConvLab#76]
Hi, 

I tried to upload my model code and pretrained weights in codalab test submission.
But, my submission.zip file has 1.6 GB.
I uploaded and waited a moment but, It didn't work.

I googled the limit of submission file in codalab and,
https://github.com/codalab/codalab-competitions/issues/1050
It seems like only about 300 MB is covered.

Q 1. Is it right to upload my pretrain weight file? 
Q 2. If yes, how to upload pretrain weight file? (The way is just uploading own files on cloud service and downloading them in my code when running?)

Thanks.

**Comment by jincli** [comment]
@jeonggwanlee  Please upload your pretrained model to cloud service and add downloading logic in your code.. .  you should be able to find similar code in ConvLab.

**Comment by jeonggwanlee** [comment]
@jincli I see. Thank you!
