### ISSUE TITLE
About the human evaluation

### ISSUE THREAD

**Issue by huanli2012** [ConvLab/ConvLab#81]
Hello, I have two questions about the human evaluation.
1. In final human evaluation, you use `task success rate ` to rank each submission. Issue #80  says that the code of computing `task success rate ` may be different in each submission. Did you fix it in human evaluation?
2. [Task proposal](http://workshop.colips.org/dstc7/dstc8/DTSC8_multidomain_task_proposal.pdf) says `task success rate, dialog length, irrelevant turn rate, redundant turn rate, user satisfaction score` will be considered in crowdworker-based evaluation while you only use `task success rate` finally.

Thank you.

**Comment by truthless11** [comment]
In human evaluation, the task success rate is provided by each crowd-worker, so the value matching issue in automatic metrics no longer exists in human evaluation.

**Comment by huanli2012** [comment]
Thanks. I also want to confirm whether each submission was scored by each crowd-worker， instead of each worker evaluating some submissions. And what about my second question?

**Comment by jincli** [comment]
@huanli2012  In human evaluation, each submission was scored by many crowd-workers, and we report the average value. 
As for your second question, the task proposal you mentioned is the one we used to apply for DSTC challenge early this year, and it is a little outdated. Now we still report other metrics including turns, user scores, etc. But if we need a one single metric for final ranking, we believe that success rate is the best one for human evaluation.  I hope this clarifies your concern.

**Comment by huanli2012** [comment]
Thus each score of each submission was offered without comparison. You did not inform you would  choose success rate as the only metric. Anyway thank you for your answer.
