### ISSUE TITLE
The architecture of MILU?

### ISSUE THREAD

**Issue by rxy1212** [ConvLab/ConvLab#98]
What is the architecture of MILU? I can`t find it in the internet, would you release the detail model architecture in the future?

**Comment by jincli** [comment]
@rxy1212  We do not have a detailed description of MILU architecture. Please check https://github.com/ConvLab/ConvLab/blob/master/convlab/modules/nlu/multiwoz/milu/model.py and https://github.com/ConvLab/ConvLab/tree/master/convlab/modules/nlu/multiwoz/milu/configs for MILU model.
